"use client";
import { useCallback, useEffect, useState } from "react";
import type { FormEvent } from "react";
import Link from "next/link";
type Account = { id: number; organizationId: number; name: string; email: string; approved: boolean };
export default function CustomerManagement({ organizations }: { organizations: { id: number; name: string }[] }) {
  const [accounts, setAccounts] = useState<Account[]>([]), [message, setMessage] = useState(""), [error, setError] = useState(""), [busy, setBusy] = useState(false);
  const load = useCallback(async () => { const response = await fetch("/api/admin/customers", { cache: "no-store" }); if (response.ok) setAccounts(await response.json()); }, []);
  useEffect(() => { void load(); }, [load]);
  async function create(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setBusy(true); setError(""); setMessage("");
    const form = event.currentTarget;
    const values = Object.fromEntries(new FormData(form));
    try { const response = await fetch("/api/admin/customers", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(values) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); setMessage("Kundenzugang angelegt. Zugangsdaten bitte persönlich über einen sicheren Kanal übergeben."); form.reset(); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Speichern fehlgeschlagen."); } finally { setBusy(false); }
  }
  async function toggle(account: Account) { const response = await fetch("/api/admin/customers", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id: account.id, approved: !account.approved }) }); if (response.ok) await load(); else setError("Status konnte nicht geändert werden."); }
  const input = "mt-2 w-full rounded-xl border border-slate-700 bg-slate-900 p-3 text-white focus:border-emerald-400 focus:outline-none";
  return <main className="mx-auto max-w-5xl px-4 py-12 sm:px-6"><Link href="/admin" className="text-sm text-emerald-300">← Zum Control Center</Link><h1 className="mt-8 text-3xl font-extrabold text-white">Kundenzugänge freigeben</h1><p className="mt-3 text-sm text-slate-400">Nur für Admins. Kunden erhalten erst nach Gespräch, Betriebseinrichtung und expliziter Freigabe Zugang zum eigenen Fuhrpark. E-Mail ist eindeutig; Passwörter werden nur als Hash gespeichert.</p>{error && <p role="alert" className="mt-5 rounded-xl bg-red-950/40 p-4 text-red-200">{error}</p>}{message && <p role="status" className="mt-5 rounded-xl bg-emerald-950/40 p-4 text-emerald-200">{message}</p>}<div className="mt-8 grid gap-6 lg:grid-cols-2"><form onSubmit={create} className="space-y-4 rounded-2xl border border-slate-800 bg-slate-950 p-6"><h2 className="text-xl font-bold text-white">Neuen Zugang erstellen</h2><label className="block text-sm text-slate-300">Betrieb *<select name="organizationId" required className={input}><option value="">Bitte wählen</option>{organizations.map((org) => <option key={org.id} value={org.id}>{org.name}</option>)}</select></label><label className="block text-sm text-slate-300">Kontaktname *<input name="name" required maxLength={120} className={input} /></label><label className="block text-sm text-slate-300">E-Mail *<input name="email" type="email" required className={input} /></label><label className="block text-sm text-slate-300">Einmaliges Startpasswort * (mindestens 12 Zeichen)<input name="password" type="password" minLength={12} maxLength={200} required autoComplete="new-password" className={input} /></label><button disabled={busy || !organizations.length} className="w-full rounded-xl bg-emerald-400 p-3 font-bold text-slate-950 disabled:opacity-50">{busy ? "Speichert …" : "Zugang erstellen und freigeben"}</button><p className="text-xs text-amber-200">Passwort nicht per unverschlüsselter E-Mail versenden. Individuelle Kundenkonten nicht für Mitarbeitende teilen.</p></form><section className="rounded-2xl border border-slate-800 bg-slate-950 p-6"><h2 className="text-xl font-bold text-white">Bestehende Zugänge</h2><div className="mt-5 space-y-3">{accounts.map((account) => <div key={account.id} className="flex items-center justify-between gap-3 rounded-xl border border-slate-800 p-3"><div><p className="font-semibold text-white">{account.name}</p><p className="text-xs text-slate-400">{account.email} · {organizations.find((org) => org.id === account.organizationId)?.name || "Betrieb"}</p></div><button type="button" onClick={() => void toggle(account)} className="shrink-0 rounded-lg border border-slate-700 px-3 py-2 text-xs text-emerald-300">{account.approved ? "Sperren" : "Aktivieren"}</button></div>)}{!accounts.length && <p className="text-sm text-slate-500">Noch keine Kundenkonten.</p>}</div></section></div></main>;
}
