import type { Metadata } from "next";
import Link from "next/link";
import { getLegalSettings, isLegalReady } from "@/lib/legal";

export const dynamic = "force-dynamic";
export const metadata: Metadata = { title: "Datenschutz", description: "Informationen zur Verarbeitung personenbezogener Daten bei Lotys Mobility." };

export default async function PrivacyPage() {
  const settings = await getLegalSettings();
  const ready = isLegalReady(settings);
  return <main className="mx-auto max-w-3xl px-4 py-12 sm:px-6 lg:py-20">
    <Link href="/" className="text-sm text-emerald-400 hover:text-emerald-300">← Zur Startseite</Link>
    <h1 className="mt-8 text-4xl font-extrabold text-white">Datenschutzhinweise</h1>
    {!ready && <div role="status" className="mt-7 rounded-2xl border border-amber-500/30 bg-amber-950/20 p-5 text-sm leading-7 text-amber-100"><strong>Betreiberangaben noch nicht freigegeben.</strong> Die folgenden Hinweise beschreiben die Verarbeitung in der Anwendung; die tatsächlichen Anbieter-, Hosting- und Kontaktdaten müssen vor dem öffentlichen Livegang im geschützten Bereich ergänzt und geprüft werden. Dieser Text ist bis dahin keine vollständig individualisierte Datenschutzerklärung.</div>}
    <article className="mt-10 space-y-9 text-sm leading-7 text-slate-300">
      <section><h2 className="text-xl font-bold text-white">1. Verantwortlicher</h2>{ready ? <p className="mt-3">{settings.businessName}, {settings.street}, {settings.postalCode} {settings.city}, {settings.country}. E-Mail: <a href={`mailto:${settings.privacyContact}`} className="text-emerald-300 underline">{settings.privacyContact}</a>{settings.phone && <>, Telefon: {settings.phone}</>}.</p> : <p className="mt-3">Der Verantwortliche muss vor Freigabe dieser Website seine vollständigen Angaben hinterlegen. Bitte übermitteln Sie bis dahin keine personenbezogenen Daten über die Formulare.</p>}</section>
      <section><h2 className="text-xl font-bold text-white">2. Kontaktformular</h2><p className="mt-3">Bei einer Kontaktanfrage verarbeiten wir Namen, E-Mail-Adresse, gegebenenfalls Unternehmen und Telefonnummer sowie Betreff und Nachricht, um die Anfrage zu bearbeiten und zu beantworten. Für vorvertragliche Anfragen kommt Art. 6 Abs. 1 lit. b DSGVO in Betracht; bei sonstigen Anfragen das berechtigte Interesse an der Bearbeitung nach Art. 6 Abs. 1 lit. f DSGVO. Die Angaben werden in einer PostgreSQL-Datenbank gespeichert und sind nur im geschützten Team-Bereich abrufbar. Es findet durch das Formular keine automatische Anmeldung für Werbe-E-Mails statt.</p></section>
      <section><h2 className="text-xl font-bold text-white">3. Serviceanfragen</h2><p className="mt-3">Für eine Serviceanfrage verarbeiten wir zusätzlich Kennzeichen, Fahrzeugmodell, Problembeschreibung, Priorität und Kontaktdaten der genannten Person. Die Angaben dienen allein der Bearbeitung des angefragten Vorgangs (Art. 6 Abs. 1 lit. b DSGVO, sofern ein Vertragsverhältnis besteht; andernfalls Art. 6 Abs. 1 lit. f DSGVO). Bitte keine Führerscheinkopien, Gesundheitsdaten, Zugangsdaten oder vertraulichen Unterlagen in Freitextfeldern übermitteln.</p></section>
      <section><h2 className="text-xl font-bold text-white">4. Fuhrpark-Check</h2><p className="mt-3">Der freiwillige Fuhrpark-Check speichert Firmen- und Kontaktdaten, Fahrzeuganzahl, Organisationsform und genannten Schwerpunkt. Hieraus wird ein unverbindlicher Orientierungswert berechnet. Eine vollautomatische Entscheidung mit rechtlicher Wirkung erfolgt nicht. Die Daten dienen der Auswertung Ihrer Anfrage und einem gewünschten Erstgespräch. Rechtsgrundlage ist Art. 6 Abs. 1 lit. b beziehungsweise lit. f DSGVO je nach konkreter Anfrage.</p></section>
      <section><h2 className="text-xl font-bold text-white">5. Empfänger, Hosting und optionale Dienste</h2><p className="mt-3">Formulareingaben werden serverseitig verarbeitet und in der angebundenen Datenbank gespeichert. {ready ? <>Der vom Betreiber angegebene Hosting-/Datenbankanbieter ist {settings.hostingProvider}; angegebener Hosting-Standort: {settings.hostingLocation}.</> : <>Der tatsächlich genutzte Hosting- und Datenbankanbieter muss vom Betreiber noch dokumentiert werden.</>} {ready && settings.processors && <>Weitere vom Betreiber angegebene Dienstleister: {settings.processors}. </>}Wenn der Betreiber die optionale E-Mail-Benachrichtigung (Resend) oder einen CRM-Webhook aktiviert, können zur Bearbeitung der Anfrage erforderliche Daten an die entsprechend konfigurierten Dienstleister übertragen werden. Die tatsächlich eingesetzten Auftragsverarbeiter und etwaige Drittlandübermittlungen sind vor Aktivierung zu prüfen und hier zu ergänzen.</p></section>
      <section><h2 className="text-xl font-bold text-white">6. Video und externe Inhalte</h2><p className="mt-3">Auf der Startseite zeigen wir einen stummen Markenfilm mit Quellenangabe. Video und Vorschaubild werden über unseren eigenen Webserver ausgeliefert; beim Seitenaufruf entsteht dadurch keine Verbindung zu Pexels. Die Nennung und Verlinkung des Urhebers führt nur dann zu Pexels, wenn Sie den Link ausdrücklich anklicken.</p></section>
      <section><h2 className="text-xl font-bold text-white">7. Notwendiges Session-Cookie und Serverprotokolle</h2><p className="mt-3">Team- und freigegebene Kundenkonten verwenden jeweils ein signiertes, auf acht Stunden begrenztes HttpOnly-Session-Cookie zur Zugangskontrolle. Die freiwillige Hell-/Dunkelmodus-Einstellung wird ausschließlich lokal in Ihrem Browser gespeichert. Die Anwendung setzt derzeit keine Analyse- oder Werbe-Cookies; daher erscheint kein Tracking-Banner. Werden künftig nicht notwendige Tracking-Dienste eingebunden, ist vorab eine passende Einwilligungslösung einzurichten. Der Hostinganbieter kann technische Zugriffsdaten in Serverlogs verarbeiten. {ready ? <>Die vom Betreiber dokumentierte geplante Log-Aufbewahrung beträgt {settings.serverLogDays} Tage; die tatsächliche Frist des Hostinganbieters muss damit abgeglichen werden.</> : <>Die tatsächliche Speicherfrist der Serverlogs muss vom Betreiber geprüft werden.</>}</p></section>
      <section><h2 className="text-xl font-bold text-white">8. Speicherdauer und Löschung</h2><p className="mt-3">Daten werden nur so lange benötigt, wie die Bearbeitung der Anfrage, gesetzliche Aufbewahrungspflichten oder die Durchsetzung von Ansprüchen es erfordern. {ready ? <>Für Anfragen ist eine geplante Prüffrist von {settings.inquiryRetentionMonths} Monaten dokumentiert.</> : <>Eine konkrete Aufbewahrungsfrist muss der Betreiber noch festlegen.</>} Im aktuellen Stand ist <strong>noch keine automatische Löschung</strong> implementiert. Der Betreiber muss den Löschprozess vor dem produktiven Umgang mit echten Kundendaten organisatorisch und technisch sicherstellen.</p></section>
      <section><h2 className="text-xl font-bold text-white">9. Ihre Rechte</h2><p className="mt-3">Sie haben nach Maßgabe der DSGVO insbesondere Rechte auf Auskunft, Berichtigung, Löschung, Einschränkung, Datenübertragbarkeit und Widerspruch. Außerdem können Sie sich bei einer zuständigen Datenschutzaufsichtsbehörde beschweren. Zur Ausübung Ihrer Rechte nutzen Sie bitte die angegebene Datenschutz-Kontaktadresse. Bei einer Verarbeitung auf Basis einer Einwilligung können Sie diese jederzeit mit Wirkung für die Zukunft widerrufen.</p></section>
      {ready && <p className="border-t border-slate-800 pt-5 text-xs text-slate-500">Zuletzt vom Betreiber aktualisiert: {settings.updatedAt.toLocaleDateString("de-DE")}</p>}
    </article>
  </main>;
}
